#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| The first thing we will do is create a new Laravel application instance
| which serves as the "glue" for all the components of Laravel, and is
| the IoC container for the system binding all of the various parts.
|
*/

$app = require_once __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Handle The Command
|--------------------------------------------------------------------------
|
| Next, we will handle the command either through the Artisan console
| application or the PHP CLI. This console application is the key to
| orchestrating all of the many bootstrapping processes.
|
*/

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(new Symfony\Component\Console\Input\ArgvInput, new Symfony\Component\Console\Output\ConsoleOutput));
